---
# tasks file for docker
- name: Docker | Install Prerequisits for APT
  apt:
    update_cache: yes
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Docker | Add repository key
  apt_key:
    url: "{{ docker_ce_gpg_key }}"
    state: present

- name: Docker | Configure Docker repository
  apt_repository:
    repo: "{{ docker_ce_apt_repo }}"
    state: present

- name: Docker | Install docker-ce
  apt:
    update_cache: yes
    name:
      - "docker-ce{{ ('=' if docker_ce_version_apt else '') ~ (docker_ce_version_apt | default(omit)) }}"
      - "docker-ce-cli{{ ('=' if docker_ce_version_apt else '') ~ (docker_ce_version_apt | default(omit)) }}"
      - containerd.io
    state: present
