---
- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    update_cache: yes
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg2
    state: present

- name: Add Docker's official GPG key
  apt_key:
    url: "{{ supported_platforms[ansible_distribution]['repo_url'] }}/gpg"
    state: present

- name: Add the Docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] {{ supported_platforms[ansible_distribution]['repo_url'] }} {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker CE
  apt:
    name:
      - "docker-ce{{ docker_version_string }}"
      - "docker-ce-cli{{ docker_version_string }}"
      - containerd.io
    state: present
  vars:
    docker_version_string: "{{ (docker_version | length > 0) | ternary('=' + docker_version, '') }}"

- name: Create /etc/docker
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Set up the Docker daemon options (json)
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  register: docker_daemon_json_state

- name: Create /etc/systemd/system/docker.service.d
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Ensure service starts at boot
  systemd:
    name: docker
    enabled: yes
    state: "{{ (docker_daemon_json_state is changed) | ternary('restarted', 'started') }}"
    daemon_reload: yes
