---
# tasks file for docker
- name: Docker | Include {{ ansible_distribution }} specific variables
  include_vars: "{{ ansible_distribution | lower }}.yml"

- name: Docker | Start Installation
  include_tasks: "{{ ansible_pkg_mgr }}.yml"

- name: Docker | Create Docker configuration directories
  file:
    path: "/etc/docker"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Docker | Configure Docker daemon options (json)
  template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Docker | Ensure service starts at boot
  become: true
  systemd:
    name: docker
    state: restarted
    enabled: yes
